services:
  redis:
    build: ./redis
    image: redis
    container_name: redis
    networks:
      - inception
    volumes:
      - "wp-data:/var/www"
    restart: on-failure

  ftp:
    build: ./ftp
    image: ftp
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ftp-data:/home/vsftpd
    env_file: .env
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
    networks:
      - inception
    restart: on-failure
  
  website:
    build: ./web
    image: website
    container_name: website
    networks:
      - inception
    restart: on-failure

  adminer:
    build: ./adminer
    image: adminer
    container_name: adminer
    networks:
      - inception
    restart: on-failure

  prometheus:
    build: ./prometheus
    image: prometheus
    container_name: prometheus
    restart: on-failure
    ports:
      - "9090:9090"
    networks:
      - inception
    volumes:
      - ./prometheus/conf/prometheus.yml:/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus/data

volumes:
  prometheus_data:
    name: prometheus_data
    driver: local
  ftp-data:
    name: ftp_data
    driver: local
